# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ListenerMapping.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ListenerMapping.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15ListenerMapping.proto\"\'\n\x12\x41vailableListeners\x12\x11\n\tlisteners\x18\x01 \x03(\t\"\xbc\x01\n\x0fListenerMapping\x12S\n\x1b\x63hannel_to_listener_mapping\x18\x01 \x03(\x0b\x32..ListenerMapping.ChannelToListenerMappingEntry\x1aT\n\x1d\x43hannelToListenerMappingEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.AvailableListeners:\x02\x38\x01'
)




_AVAILABLELISTENERS = _descriptor.Descriptor(
  name='AvailableListeners',
  full_name='AvailableListeners',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='listeners', full_name='AvailableListeners.listeners', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=64,
)


_LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY = _descriptor.Descriptor(
  name='ChannelToListenerMappingEntry',
  full_name='ListenerMapping.ChannelToListenerMappingEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='ListenerMapping.ChannelToListenerMappingEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ListenerMapping.ChannelToListenerMappingEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=255,
)

_LISTENERMAPPING = _descriptor.Descriptor(
  name='ListenerMapping',
  full_name='ListenerMapping',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_to_listener_mapping', full_name='ListenerMapping.channel_to_listener_mapping', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=255,
)

_LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY.fields_by_name['value'].message_type = _AVAILABLELISTENERS
_LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY.containing_type = _LISTENERMAPPING
_LISTENERMAPPING.fields_by_name['channel_to_listener_mapping'].message_type = _LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY
DESCRIPTOR.message_types_by_name['AvailableListeners'] = _AVAILABLELISTENERS
DESCRIPTOR.message_types_by_name['ListenerMapping'] = _LISTENERMAPPING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AvailableListeners = _reflection.GeneratedProtocolMessageType('AvailableListeners', (_message.Message,), {
  'DESCRIPTOR' : _AVAILABLELISTENERS,
  '__module__' : 'ListenerMapping_pb2'
  # @@protoc_insertion_point(class_scope:AvailableListeners)
  })
_sym_db.RegisterMessage(AvailableListeners)

ListenerMapping = _reflection.GeneratedProtocolMessageType('ListenerMapping', (_message.Message,), {

  'ChannelToListenerMappingEntry' : _reflection.GeneratedProtocolMessageType('ChannelToListenerMappingEntry', (_message.Message,), {
    'DESCRIPTOR' : _LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY,
    '__module__' : 'ListenerMapping_pb2'
    # @@protoc_insertion_point(class_scope:ListenerMapping.ChannelToListenerMappingEntry)
    })
  ,
  'DESCRIPTOR' : _LISTENERMAPPING,
  '__module__' : 'ListenerMapping_pb2'
  # @@protoc_insertion_point(class_scope:ListenerMapping)
  })
_sym_db.RegisterMessage(ListenerMapping)
_sym_db.RegisterMessage(ListenerMapping.ChannelToListenerMappingEntry)


_LISTENERMAPPING_CHANNELTOLISTENERMAPPINGENTRY._options = None
# @@protoc_insertion_point(module_scope)
