# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WordlDb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rWordlDb.proto\"V\n\nGameRecord\x12\x0c\n\x04game\x18\x01 \x01(\t\x12\x10\n\x08\x61ttempts\x18\x02 \x01(\x05\x12\x14\n\x0cmax_attempts\x18\x03 \x01(\x05\x12\x12\n\nextra_data\x18\x04 \x01(\t\"\x1c\n\x0cGameModifier\x12\x0c\n\x04game\x18\x01 \x01(\t\"*\n\x0cUserModifier\x12\x1a\n\x12suggested_starters\x18\x01 \x03(\t\"\xa8\x03\n\nUserRecord\x12\x17\n\x0flast_known_name\x18\x03 \x01(\t\x12$\n\ruser_modifier\x18\x05 \x01(\x0b\x32\r.UserModifier\x12\x34\n\rclassic_games\x18\x01 \x03(\x0b\x32\x1d.UserRecord.ClassicGamesEntry\x12\x32\n\x0c\x63ustom_games\x18\x02 \x03(\x0b\x32\x1c.UserRecord.CustomGamesEntry\x12-\n\tmodifiers\x18\x04 \x03(\x0b\x32\x1a.UserRecord.ModifiersEntry\x1a@\n\x11\x43lassicGamesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.GameRecord:\x02\x38\x01\x1a?\n\x10\x43ustomGamesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.GameRecord:\x02\x38\x01\x1a?\n\x0eModifiersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.GameModifier:\x02\x38\x01\"<\n\x13\x44\x61ilySeasonModifier\x12\x12\n\nidentifier\x18\x01 \x01(\t\x12\x11\n\tword_pool\x18\x02 \x03(\t\"\xc0\x01\n\x0cWordleSeason\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\'\n\x05users\x18\x03 \x03(\x0b\x32\x18.WordleSeason.UsersEntry\x12,\n\x0e\x64\x61ily_modifier\x18\x04 \x03(\x0b\x32\x14.DailySeasonModifier\x1a\x39\n\nUsersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.UserRecord:\x02\x38\x01\"\xd2\x01\n\x11WordlSeasonFileDb\x12\x14\n\x0c\x63urrent_file\x18\x01 \x01(\t\x12\x1b\n\x13\x63urrent_season_name\x18\x02 \x01(\t\x12M\n\x17\x66ilename_to_season_name\x18\x03 \x03(\x0b\x32,.WordlSeasonFileDb.FilenameToSeasonNameEntry\x1a;\n\x19\x46ilenameToSeasonNameEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01')



_GAMERECORD = DESCRIPTOR.message_types_by_name['GameRecord']
_GAMEMODIFIER = DESCRIPTOR.message_types_by_name['GameModifier']
_USERMODIFIER = DESCRIPTOR.message_types_by_name['UserModifier']
_USERRECORD = DESCRIPTOR.message_types_by_name['UserRecord']
_USERRECORD_CLASSICGAMESENTRY = _USERRECORD.nested_types_by_name['ClassicGamesEntry']
_USERRECORD_CUSTOMGAMESENTRY = _USERRECORD.nested_types_by_name['CustomGamesEntry']
_USERRECORD_MODIFIERSENTRY = _USERRECORD.nested_types_by_name['ModifiersEntry']
_DAILYSEASONMODIFIER = DESCRIPTOR.message_types_by_name['DailySeasonModifier']
_WORDLESEASON = DESCRIPTOR.message_types_by_name['WordleSeason']
_WORDLESEASON_USERSENTRY = _WORDLESEASON.nested_types_by_name['UsersEntry']
_WORDLSEASONFILEDB = DESCRIPTOR.message_types_by_name['WordlSeasonFileDb']
_WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY = _WORDLSEASONFILEDB.nested_types_by_name['FilenameToSeasonNameEntry']
GameRecord = _reflection.GeneratedProtocolMessageType('GameRecord', (_message.Message,), {
  'DESCRIPTOR' : _GAMERECORD,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:GameRecord)
  })
_sym_db.RegisterMessage(GameRecord)

GameModifier = _reflection.GeneratedProtocolMessageType('GameModifier', (_message.Message,), {
  'DESCRIPTOR' : _GAMEMODIFIER,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:GameModifier)
  })
_sym_db.RegisterMessage(GameModifier)

UserModifier = _reflection.GeneratedProtocolMessageType('UserModifier', (_message.Message,), {
  'DESCRIPTOR' : _USERMODIFIER,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:UserModifier)
  })
_sym_db.RegisterMessage(UserModifier)

UserRecord = _reflection.GeneratedProtocolMessageType('UserRecord', (_message.Message,), {

  'ClassicGamesEntry' : _reflection.GeneratedProtocolMessageType('ClassicGamesEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERRECORD_CLASSICGAMESENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:UserRecord.ClassicGamesEntry)
    })
  ,

  'CustomGamesEntry' : _reflection.GeneratedProtocolMessageType('CustomGamesEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERRECORD_CUSTOMGAMESENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:UserRecord.CustomGamesEntry)
    })
  ,

  'ModifiersEntry' : _reflection.GeneratedProtocolMessageType('ModifiersEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERRECORD_MODIFIERSENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:UserRecord.ModifiersEntry)
    })
  ,
  'DESCRIPTOR' : _USERRECORD,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:UserRecord)
  })
_sym_db.RegisterMessage(UserRecord)
_sym_db.RegisterMessage(UserRecord.ClassicGamesEntry)
_sym_db.RegisterMessage(UserRecord.CustomGamesEntry)
_sym_db.RegisterMessage(UserRecord.ModifiersEntry)

DailySeasonModifier = _reflection.GeneratedProtocolMessageType('DailySeasonModifier', (_message.Message,), {
  'DESCRIPTOR' : _DAILYSEASONMODIFIER,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:DailySeasonModifier)
  })
_sym_db.RegisterMessage(DailySeasonModifier)

WordleSeason = _reflection.GeneratedProtocolMessageType('WordleSeason', (_message.Message,), {

  'UsersEntry' : _reflection.GeneratedProtocolMessageType('UsersEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORDLESEASON_USERSENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:WordleSeason.UsersEntry)
    })
  ,
  'DESCRIPTOR' : _WORDLESEASON,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:WordleSeason)
  })
_sym_db.RegisterMessage(WordleSeason)
_sym_db.RegisterMessage(WordleSeason.UsersEntry)

WordlSeasonFileDb = _reflection.GeneratedProtocolMessageType('WordlSeasonFileDb', (_message.Message,), {

  'FilenameToSeasonNameEntry' : _reflection.GeneratedProtocolMessageType('FilenameToSeasonNameEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:WordlSeasonFileDb.FilenameToSeasonNameEntry)
    })
  ,
  'DESCRIPTOR' : _WORDLSEASONFILEDB,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:WordlSeasonFileDb)
  })
_sym_db.RegisterMessage(WordlSeasonFileDb)
_sym_db.RegisterMessage(WordlSeasonFileDb.FilenameToSeasonNameEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERRECORD_CLASSICGAMESENTRY._options = None
  _USERRECORD_CLASSICGAMESENTRY._serialized_options = b'8\001'
  _USERRECORD_CUSTOMGAMESENTRY._options = None
  _USERRECORD_CUSTOMGAMESENTRY._serialized_options = b'8\001'
  _USERRECORD_MODIFIERSENTRY._options = None
  _USERRECORD_MODIFIERSENTRY._serialized_options = b'8\001'
  _WORDLESEASON_USERSENTRY._options = None
  _WORDLESEASON_USERSENTRY._serialized_options = b'8\001'
  _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY._options = None
  _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY._serialized_options = b'8\001'
  _GAMERECORD._serialized_start=17
  _GAMERECORD._serialized_end=103
  _GAMEMODIFIER._serialized_start=105
  _GAMEMODIFIER._serialized_end=133
  _USERMODIFIER._serialized_start=135
  _USERMODIFIER._serialized_end=177
  _USERRECORD._serialized_start=180
  _USERRECORD._serialized_end=604
  _USERRECORD_CLASSICGAMESENTRY._serialized_start=410
  _USERRECORD_CLASSICGAMESENTRY._serialized_end=474
  _USERRECORD_CUSTOMGAMESENTRY._serialized_start=476
  _USERRECORD_CUSTOMGAMESENTRY._serialized_end=539
  _USERRECORD_MODIFIERSENTRY._serialized_start=541
  _USERRECORD_MODIFIERSENTRY._serialized_end=604
  _DAILYSEASONMODIFIER._serialized_start=606
  _DAILYSEASONMODIFIER._serialized_end=666
  _WORDLESEASON._serialized_start=669
  _WORDLESEASON._serialized_end=861
  _WORDLESEASON_USERSENTRY._serialized_start=804
  _WORDLESEASON_USERSENTRY._serialized_end=861
  _WORDLSEASONFILEDB._serialized_start=864
  _WORDLSEASONFILEDB._serialized_end=1074
  _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY._serialized_start=1015
  _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY._serialized_end=1074
# @@protoc_insertion_point(module_scope)
