# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WordlDb.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='WordlDb.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rWordlDb.proto\"V\n\nGameRecord\x12\x0c\n\x04game\x18\x01 \x01(\t\x12\x10\n\x08\x61ttempts\x18\x02 \x01(\x05\x12\x14\n\x0cmax_attempts\x18\x03 \x01(\x05\x12\x12\n\nextra_data\x18\x04 \x01(\t\"\x92\x02\n\nUserRecord\x12\x17\n\x0flast_known_name\x18\x03 \x01(\t\x12\x34\n\rclassic_games\x18\x01 \x03(\x0b\x32\x1d.UserRecord.ClassicGamesEntry\x12\x32\n\x0c\x63ustom_games\x18\x02 \x03(\x0b\x32\x1c.UserRecord.CustomGamesEntry\x1a@\n\x11\x43lassicGamesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.GameRecord:\x02\x38\x01\x1a?\n\x10\x43ustomGamesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.GameRecord:\x02\x38\x01\"\x92\x01\n\x0cWordleSeason\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\'\n\x05users\x18\x03 \x03(\x0b\x32\x18.WordleSeason.UsersEntry\x1a\x39\n\nUsersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1a\n\x05value\x18\x02 \x01(\x0b\x32\x0b.UserRecord:\x02\x38\x01\"\xd2\x01\n\x11WordlSeasonFileDb\x12\x14\n\x0c\x63urrent_file\x18\x01 \x01(\t\x12\x1b\n\x13\x63urrent_season_name\x18\x02 \x01(\t\x12M\n\x17\x66ilename_to_season_name\x18\x03 \x03(\x0b\x32,.WordlSeasonFileDb.FilenameToSeasonNameEntry\x1a;\n\x19\x46ilenameToSeasonNameEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01'
)




_GAMERECORD = _descriptor.Descriptor(
  name='GameRecord',
  full_name='GameRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='GameRecord.game', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attempts', full_name='GameRecord.attempts', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_attempts', full_name='GameRecord.max_attempts', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extra_data', full_name='GameRecord.extra_data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=103,
)


_USERRECORD_CLASSICGAMESENTRY = _descriptor.Descriptor(
  name='ClassicGamesEntry',
  full_name='UserRecord.ClassicGamesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='UserRecord.ClassicGamesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='UserRecord.ClassicGamesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=315,
)

_USERRECORD_CUSTOMGAMESENTRY = _descriptor.Descriptor(
  name='CustomGamesEntry',
  full_name='UserRecord.CustomGamesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='UserRecord.CustomGamesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='UserRecord.CustomGamesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=380,
)

_USERRECORD = _descriptor.Descriptor(
  name='UserRecord',
  full_name='UserRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='last_known_name', full_name='UserRecord.last_known_name', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classic_games', full_name='UserRecord.classic_games', index=1,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='custom_games', full_name='UserRecord.custom_games', index=2,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_USERRECORD_CLASSICGAMESENTRY, _USERRECORD_CUSTOMGAMESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=106,
  serialized_end=380,
)


_WORDLESEASON_USERSENTRY = _descriptor.Descriptor(
  name='UsersEntry',
  full_name='WordleSeason.UsersEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='WordleSeason.UsersEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='WordleSeason.UsersEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=529,
)

_WORDLESEASON = _descriptor.Descriptor(
  name='WordleSeason',
  full_name='WordleSeason',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='WordleSeason.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename', full_name='WordleSeason.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='users', full_name='WordleSeason.users', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WORDLESEASON_USERSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=529,
)


_WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY = _descriptor.Descriptor(
  name='FilenameToSeasonNameEntry',
  full_name='WordlSeasonFileDb.FilenameToSeasonNameEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='WordlSeasonFileDb.FilenameToSeasonNameEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='WordlSeasonFileDb.FilenameToSeasonNameEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=683,
  serialized_end=742,
)

_WORDLSEASONFILEDB = _descriptor.Descriptor(
  name='WordlSeasonFileDb',
  full_name='WordlSeasonFileDb',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='current_file', full_name='WordlSeasonFileDb.current_file', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_season_name', full_name='WordlSeasonFileDb.current_season_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='filename_to_season_name', full_name='WordlSeasonFileDb.filename_to_season_name', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=532,
  serialized_end=742,
)

_USERRECORD_CLASSICGAMESENTRY.fields_by_name['value'].message_type = _GAMERECORD
_USERRECORD_CLASSICGAMESENTRY.containing_type = _USERRECORD
_USERRECORD_CUSTOMGAMESENTRY.fields_by_name['value'].message_type = _GAMERECORD
_USERRECORD_CUSTOMGAMESENTRY.containing_type = _USERRECORD
_USERRECORD.fields_by_name['classic_games'].message_type = _USERRECORD_CLASSICGAMESENTRY
_USERRECORD.fields_by_name['custom_games'].message_type = _USERRECORD_CUSTOMGAMESENTRY
_WORDLESEASON_USERSENTRY.fields_by_name['value'].message_type = _USERRECORD
_WORDLESEASON_USERSENTRY.containing_type = _WORDLESEASON
_WORDLESEASON.fields_by_name['users'].message_type = _WORDLESEASON_USERSENTRY
_WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY.containing_type = _WORDLSEASONFILEDB
_WORDLSEASONFILEDB.fields_by_name['filename_to_season_name'].message_type = _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY
DESCRIPTOR.message_types_by_name['GameRecord'] = _GAMERECORD
DESCRIPTOR.message_types_by_name['UserRecord'] = _USERRECORD
DESCRIPTOR.message_types_by_name['WordleSeason'] = _WORDLESEASON
DESCRIPTOR.message_types_by_name['WordlSeasonFileDb'] = _WORDLSEASONFILEDB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameRecord = _reflection.GeneratedProtocolMessageType('GameRecord', (_message.Message,), {
  'DESCRIPTOR' : _GAMERECORD,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:GameRecord)
  })
_sym_db.RegisterMessage(GameRecord)

UserRecord = _reflection.GeneratedProtocolMessageType('UserRecord', (_message.Message,), {

  'ClassicGamesEntry' : _reflection.GeneratedProtocolMessageType('ClassicGamesEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERRECORD_CLASSICGAMESENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:UserRecord.ClassicGamesEntry)
    })
  ,

  'CustomGamesEntry' : _reflection.GeneratedProtocolMessageType('CustomGamesEntry', (_message.Message,), {
    'DESCRIPTOR' : _USERRECORD_CUSTOMGAMESENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:UserRecord.CustomGamesEntry)
    })
  ,
  'DESCRIPTOR' : _USERRECORD,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:UserRecord)
  })
_sym_db.RegisterMessage(UserRecord)
_sym_db.RegisterMessage(UserRecord.ClassicGamesEntry)
_sym_db.RegisterMessage(UserRecord.CustomGamesEntry)

WordleSeason = _reflection.GeneratedProtocolMessageType('WordleSeason', (_message.Message,), {

  'UsersEntry' : _reflection.GeneratedProtocolMessageType('UsersEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORDLESEASON_USERSENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:WordleSeason.UsersEntry)
    })
  ,
  'DESCRIPTOR' : _WORDLESEASON,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:WordleSeason)
  })
_sym_db.RegisterMessage(WordleSeason)
_sym_db.RegisterMessage(WordleSeason.UsersEntry)

WordlSeasonFileDb = _reflection.GeneratedProtocolMessageType('WordlSeasonFileDb', (_message.Message,), {

  'FilenameToSeasonNameEntry' : _reflection.GeneratedProtocolMessageType('FilenameToSeasonNameEntry', (_message.Message,), {
    'DESCRIPTOR' : _WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY,
    '__module__' : 'WordlDb_pb2'
    # @@protoc_insertion_point(class_scope:WordlSeasonFileDb.FilenameToSeasonNameEntry)
    })
  ,
  'DESCRIPTOR' : _WORDLSEASONFILEDB,
  '__module__' : 'WordlDb_pb2'
  # @@protoc_insertion_point(class_scope:WordlSeasonFileDb)
  })
_sym_db.RegisterMessage(WordlSeasonFileDb)
_sym_db.RegisterMessage(WordlSeasonFileDb.FilenameToSeasonNameEntry)


_USERRECORD_CLASSICGAMESENTRY._options = None
_USERRECORD_CUSTOMGAMESENTRY._options = None
_WORDLESEASON_USERSENTRY._options = None
_WORDLSEASONFILEDB_FILENAMETOSEASONNAMEENTRY._options = None
# @@protoc_insertion_point(module_scope)
